config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root to: 'rooms#index'
  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :chats, only: [:index, :create]

    namespace :api do
      resources :chats, only: :index, defaults: { format: 'json' }
    end
  end
  get 'rooms/:room_id/chats', to: 'chats#index'
  post 'rooms/:room_id/chats', to: 'chats#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :room

  mount_uploader :image, ImageUploader
end

app/models/message.rb
class Message < ApplicationRecord
  
  mount_uploader :avatar, AvatarUploader

  belongs_to :user
  belongs_to :room

  validates :content, presence: true, length: { maximum: 500 }

  def template
    ApplicationController.renderer.render partial: 'messages/message', locals: { message: self }
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates :name, presence: true
  validates :chosen_time, presence: true
  validates :chosen_time, numericality: { only_integer: true ,greater_than_or_equal: 0, less_than: 25}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy

  validates :name, presence: true

  def self.guest
    find_or_create_by(email: 'guest@example.com') do |user|
      user.name = Faker::Name.first_name
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.guest2
    find_or_create_by(email: 'guest2@example.com') do |user|
      user.name = Faker::Name.last_name
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/api/chats_controller.rb
class Api::ChatsController < ApplicationController
  def index

      # そのグループの情報をインスタンス変数@groupに保存
      @room = Room.find(params[:room_id])
      # idがパラメータで取得するidよりも大きいものを、@groupと関連するメッセージの中から検索する。
      # includesはN+1問題対策
      @new_chats = @room.messages.where('id > ?', params[:id])

      # html形式とjson形式のリクエストでそれぞれ振り分ける
      respond_to do |format|
          format.html
          format.json
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def index
    @rooms = Room.all
    @room = Room.find(params[:room_id])
    @chat = Chat.new
    @chats = @room.chats.includes(:room).order(id: "DESC")
    if (@room.created_at < Time.now - (24.hours))
      Room.destroy_by("created_at < ?", Time.now - (24.hours))
      redirect_to root_path
    end

  end

  def create
    @chat = Chat.create(chat_params)
    render json:{ chat: @chat }

    ActionCable.server.broadcast 'room_channel', message: @message.template
  end

  private

  def chat_params
    # params.require(:chat).permit(nickname: params[:nickname], message: params[:message], image: params[:image] ).merge(room_id: params[:room_id])
    params.require(:chat).permit(:nickname, :message, :image).merge(room_id: params[:room_id])
  end

end

app/controllers/concerns/check_expired_rooms.rb
module CheckExpiredRooms
  extend ActiveSupport::Concern

  def check_expired_room
    expired_rooms = Room.where("created_at < ?", Time.now - (24.hours))
    if expired_rooms.present?
      expired_rooms.destroy_all
      redirect_to root_path, notice: "Room's over!!"
    end
  end
end

app/controllers/concerns/rooms_checker.rb
module RoomsChecker
  extend ActiveSupport::Concern
  # rooms#indexで24時間経過したルームを削除します
  def check_expired_room
    expired_rooms = Room.where("created_at < ?", Time.now - 24.hours)
    if expired_rooms.present?
      expired_rooms.destroy_all
      redirect_to root_path, notice: "Room's over!!"
    end
  end
  # rooms#showでテスト,時間切れのルームを削除します
  def check_test_or_expired_room(room)
    if room.chosen_time == 0
      if room.created_at < (Time.now - 30.seconds)
        room.destroy
        redirect_to root_path, notice: "Room's over!!"
      end
    elsif room.created_at < (Time.now - room.chosen_time.hours)
      room.destroy
      redirect_to root_path, notice: "Room's over!!"
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.create(message_params)
    ActionCable.server.broadcast 'room_channel', message: @message.template
  end

  private

  def message_params
    params.require(:message).permit(:content, :avatar).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include RoomsChecker
  before_action :authenticate_user!, except: :index

  def index
    @room = Room.new
    @rooms = Room.all.order(id: 'desc')
    check_expired_room
  end

  def create
    redirect_to new_session_path  unless user_signed_in?
    @room = Room.create(room_params)
    redirect_to root_path
  end

  def show
    begin
      @room = Room.find(params[:id])
      @messages = @room.messages.includes(:user).order(:id).last(100)
      @message = current_user.messages.build
      check_test_or_expired_room(@room)
    rescue
      redirect_to root_path, notice: "Room's over!!"
    end
  end

  def show_additionally
    @room = Room.find(params[:id])
    last_id = params[:oldest_message_id].to_i - 1
    @messages = @room.messages.includes(:user).order(id: 'desc').where(id:1..last_id).last(50)
  end

  private

  def room_params
    params.require(:room).permit(:name, :chosen_time)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました"
  end

  def new_guest2
    user2 = User.guest2
    sign_in user2
    redirect_to root_path, notice: "ゲストユーザー2としてログインしました"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/chats/index.html.erb
  <div class="chat-header">
    <strong><%= @room.name %></strong>
  </div>

<div class="chat-room">
  <div class="side-bar">
    <%= render "shared/side_bar" %>
  </div>

  <div class="chat-form">
    <%= form_with model: [@room, @chat], id: "form", local: true do |f| %>
      <div class="form" data-id=<%= @room.id%> >
        <%= f.text_field :nickname, class:"form-name btn-block", placeholder:"Type a Name", id:"name", autofocus: true %>
        <%= f.text_area :message, class:"form-message", placeholder:"Type a Message", id:"message" %>
        <%= f.file_field :image, class:"form-image", id:"image" %>
        <%= f.submit "投稿", class:"form-submit", id:"submit" %>
        <%= link_to "戻る", root_path, class: "back-btn", id:"btn" %>
      </div>
    <% end %>

    <div id="list">
    </div>

    <div class="chat-main">
      <% @chats.each do |chat| %>
        <div class="chat-upper" chat-id=<%= chat.id %> >
          名前: <%= chat.nickname %> 投稿日時: <%= chat.created_at %>
        </div>
        <div class="chat-lower">
          <div>
            <%= chat.message %>
          </div>
          <% if chat.image? %>
            <%= image_tag chat.image.url %>
          <% end %>
        </div>
      <% end %>
    </div>
    
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message" id="message-<%= message.id %>">
  <p><%= message.id %>: <%= message.user.name %>: <%= l message.created_at, format: '%Y年%-m月%-d日(%a) %H:%M' %></p>
  <%= simple_format(h(message.content)) %>
  <% if message.avatar? %>
    <%= image_tag message.avatar.url %>
  <% end %>
</div>

app/views/messages/create.js.erb
document.getElementById('message_content').value = ''
document.getElementById('message_avatar').value = ''
document.getElementById('image-info').value = ''
scrollToBottom()

app/views/rooms/_footer.html.erb
<footer class="fixed-bottom" id="footer">
  <%= form_with model: [@room, @message] do |f| %>
    <div class="form-group" room-id=<%= @room.id %>>
      <%= f.text_area :content, class: 'form-control',placeholder: "メッセージを入力してください",  rows: 1, maxlength: '500' %>
    </div>
<div class="input-group">
    <label class="input-group-btn">
        <span class="btn btn-info">
            Image <%= f.file_field :avatar, style: "display: none" %>
        </span>
    </label>
    <input type="text" id="image-info" class="form-control" readonly="">
</div>

    <div class="form-group">
      <%= f.submit '送信', class: 'btn btn-primary btn-block disabled', id: 'message-button' %>
    </div>
  <% end %>
</footer>

app/views/rooms/index.html.erb
<%= render 'shared/flash_messages' %>

<%= render 'shared/form' %>

<div class="container-form">
  <% @rooms.each do |room| %>
  <div class="alert alert-light">
    <%= link_to room.name, room_path(room) %>
    <div class="room-time">
      <%= (room.created_at + room.chosen_time.hour).strftime("%m月%d日 %H:%M") %> 終了
    </div>
  </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<div class="wrapper">
  <div class="room-form">
    <%= form_with model: @room, local: true do |f| %>
      <%= f.text_field :name, class:"room-name-form", placeholder:"Type a Room Name", autofocus: true %>
      <%= f.submit "作成", class:"room-btn" %>
      <%= link_to "戻る", root_path, class:"room-back-btn" %>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div id="message-container">
    <%= render @messages %>
</div>
<%= render 'footer' %>

app/views/rooms/show_additionally.js.erb
var messageHeight = messageContainer.scrollHeight
// 今回は上からメッセージを追加
messageContainer.insertAdjacentHTML('afterbegin', "<%= j(render @messages) %>")
var newMessageHeight = messageContainer.scrollHeight
window.scrollBy(0, newMessageHeight - messageHeight)
// メッセージが存在するときだけ，読み込み可能とする
<% if @messages.present? %>
    showAdditionally = true
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
footer
</div>

app/views/shared/_form.html.erb
<div class="container-form">
  <%= form_with model: @room, local: true do |f| %>
  <div class="input-group mb-3">
    <%= f.text_field :name, class:"form-control", placeholder: 'ルーム名を入力し制限時間を選択してください', aria_label:"Recipient's username", aria_describedby:"button-addon2", required: true, autofocus: true %>
    <div class="input-group-append">
    <%= f.number_field :chosen_time, class:"form-control", value: 0, required: true, min: 0, max: 24  %>
      <%= f.submit '作成', class:'btn btn-primary' %>
    </div>
  <% end %>
  </div><span class="notice-time">※※【テスト用】制限時間を0にすると1分でルームが削除されます ※※</span>
</div>

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <%= link_to image_tag("cooltext364460306406263.png", class: 'navbar-brand'), "/" %>
    
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'アカウント編集', edit_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item active">
          <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to "ゲストログイン1",  users_guest_sign_in_path, method: :post, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to "ゲストログイン2",  users_guest2_sign_in_path, method: :post, class: 'nav-link' %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_side_bar.html.erb
<div class="room-wrapper">
side_bar
  <div class="room-lists">
    <% @rooms.each do |room| %>
      <div class="list">
        <%= link_to room.name, room_chats_path(room) %>
      </div>
    <% end %>
  </div>
</div>